import type { NicheGroup } from './types'

/**
 * Niches — the "what I actually work on" dimension.
 *
 * Every niche appears exactly once. Labels that showed up under two headings
 * (Business Development in both Business and Sales; Biotechnology in both
 * Science and Healthcare) live in their most natural group and carry the other
 * reading as an alias, so search still finds them and the database never holds
 * two rows meaning the same thing.
 */
export const NICHE_GROUPS: NicheGroup[] = [
  {
    slug: 'technology',
    name: 'Technology',
    blurb: 'People who build and run software, hardware and the systems underneath.',
    niches: [
      { slug: 'software-engineering', name: 'Software Engineering', group: 'technology', aliases: ['Software Development', 'Programming'] },
      { slug: 'ai', name: 'AI', group: 'technology', aliases: ['Artificial Intelligence', 'Generative AI', 'LLMs'] },
      { slug: 'machine-learning', name: 'Machine Learning', group: 'technology', aliases: ['ML', 'Deep Learning'] },
      { slug: 'data-science', name: 'Data Science', group: 'technology', aliases: ['Analytics', 'Data Analytics'] },
      { slug: 'cybersecurity', name: 'Cybersecurity', group: 'technology', aliases: ['Security', 'InfoSec', 'Information Security'] },
      { slug: 'cloud-computing', name: 'Cloud Computing', group: 'technology', aliases: ['Cloud', 'AWS', 'Azure', 'GCP'] },
      { slug: 'devops', name: 'DevOps', group: 'technology', aliases: ['SRE', 'Site Reliability', 'Platform Engineering', 'Infrastructure'] },
      { slug: 'web-development', name: 'Web Development', group: 'technology', aliases: ['Frontend', 'Backend', 'Full-Stack'] },
      { slug: 'mobile-development', name: 'Mobile Development', group: 'technology', aliases: ['iOS', 'Android', 'React Native', 'Flutter'] },
      { slug: 'blockchain', name: 'Blockchain', group: 'technology', aliases: ['Web3', 'Crypto', 'Smart Contracts'] },
      { slug: 'robotics', name: 'Robotics', group: 'technology', aliases: ['Autonomous Systems'] },
      { slug: 'hardware', name: 'Hardware', group: 'technology', aliases: ['Embedded', 'Firmware'] },
      { slug: 'semiconductors', name: 'Semiconductors', group: 'technology', aliases: ['Chip Design', 'VLSI', 'ASIC', 'FPGA'] },
      { slug: 'ar-vr', name: 'AR/VR', group: 'technology', aliases: ['XR', 'Spatial Computing', 'Augmented Reality', 'Virtual Reality'] },
      { slug: 'gaming', name: 'Gaming', group: 'technology', aliases: ['Game Development', 'Unity', 'Unreal'] },
      { slug: 'quantum-computing', name: 'Quantum Computing', group: 'technology', aliases: ['Quantum'] },
    ],
  },
  {
    slug: 'business',
    name: 'Business',
    blurb: 'Founders, investors and the people who decide where capital and strategy go.',
    niches: [
      { slug: 'entrepreneurship', name: 'Entrepreneurship', group: 'business', aliases: ['Founding', 'Solo Founder'] },
      { slug: 'startups', name: 'Startups', group: 'business', aliases: ['Early Stage'] },
      { slug: 'venture-capital', name: 'Venture Capital', group: 'business', aliases: ['VC', 'Seed Investing'] },
      { slug: 'private-equity', name: 'Private Equity', group: 'business', aliases: ['PE', 'Buyouts'] },
      { slug: 'investing', name: 'Investing', group: 'business', aliases: ['Angel Investing', 'Public Markets'] },
      { slug: 'management-consulting', name: 'Management Consulting', group: 'business', aliases: ['Consulting'] },
      { slug: 'strategy', name: 'Strategy', group: 'business', aliases: ['Corporate Strategy', 'Strategy & Operations'] },
      { slug: 'operations', name: 'Operations', group: 'business', aliases: ['BizOps', 'Business Operations'] },
      { slug: 'corporate-development', name: 'Corporate Development', group: 'business', aliases: ['M&A', 'Corp Dev', 'Corporate Venture Capital'] },
    ],
  },
  {
    slug: 'product-design',
    name: 'Product & Design',
    blurb: 'The people who decide what gets built and how it feels to use.',
    niches: [
      { slug: 'product-management', name: 'Product Management', group: 'product-design', aliases: ['PM', 'Product'] },
      { slug: 'product-design', name: 'Product Design', group: 'product-design', aliases: ['Design'] },
      { slug: 'ux', name: 'UX', group: 'product-design', aliases: ['User Experience', 'Interaction Design'] },
      { slug: 'ui', name: 'UI', group: 'product-design', aliases: ['User Interface', 'Visual Design', 'Design Systems'] },
      { slug: 'ux-research', name: 'UX Research', group: 'product-design', aliases: ['User Research', 'Design Research'] },
      { slug: 'graphic-design', name: 'Graphic Design', group: 'product-design', aliases: ['Visual Communication'] },
      { slug: 'branding', name: 'Branding', group: 'product-design', aliases: ['Brand Identity', 'Brand Strategy'] },
      { slug: 'industrial-design', name: 'Industrial Design', group: 'product-design', aliases: ['Product Design (Physical)'] },
    ],
  },
  {
    slug: 'growth-marketing',
    name: 'Growth & Marketing',
    blurb: 'Everyone whose job is getting the right people to notice and stay.',
    niches: [
      { slug: 'growth', name: 'Growth', group: 'growth-marketing', aliases: ['Growth Hacking', 'Retention', 'Lifecycle'] },
      { slug: 'growth-engineering', name: 'Growth Engineering', group: 'growth-marketing', aliases: ['Growth Engineer'] },
      { slug: 'performance-marketing', name: 'Performance Marketing', group: 'growth-marketing', aliases: ['Paid Media', 'Paid Acquisition', 'SEM', 'User Acquisition'] },
      { slug: 'seo', name: 'SEO', group: 'growth-marketing', aliases: ['Search Engine Optimisation', 'Organic Search'] },
      { slug: 'content-marketing', name: 'Content Marketing', group: 'growth-marketing', aliases: ['Content Strategy'] },
      { slug: 'social-media', name: 'Social Media', group: 'growth-marketing', aliases: ['Social'] },
      { slug: 'influencer-marketing', name: 'Influencer Marketing', group: 'growth-marketing', aliases: ['Creator Partnerships'] },
      { slug: 'brand-marketing', name: 'Brand Marketing', group: 'growth-marketing', aliases: ['Brand'] },
      { slug: 'product-marketing', name: 'Product Marketing', group: 'growth-marketing', aliases: ['PMM'] },
      { slug: 'advertising', name: 'Advertising', group: 'growth-marketing', aliases: ['Ads', 'Media Buying'] },
      { slug: 'public-relations', name: 'Public Relations', group: 'growth-marketing', aliases: ['PR', 'Communications'] },
      { slug: 'community', name: 'Community', group: 'growth-marketing', aliases: ['Community Management', 'DevRel', 'Developer Relations'] },
    ],
  },
  {
    slug: 'sales',
    name: 'Sales',
    blurb: 'The people carrying a number, and the ones who make that possible.',
    niches: [
      { slug: 'sales', name: 'Sales', group: 'sales', aliases: ['Inside Sales', 'Field Sales', 'Revenue'] },
      { slug: 'enterprise-sales', name: 'Enterprise Sales', group: 'sales', aliases: ['Enterprise AE', 'Strategic Accounts'] },
      { slug: 'business-development', name: 'Business Development', group: 'sales', aliases: ['BD', 'BDR', 'SDR'] },
      { slug: 'partnerships', name: 'Partnerships', group: 'sales', aliases: ['Channel', 'Alliances', 'Strategic Partnerships'] },
      { slug: 'account-management', name: 'Account Management', group: 'sales', aliases: ['Customer Success', 'Client Services'] },
      { slug: 'sales-engineering', name: 'Sales Engineering', group: 'sales', aliases: ['Solutions Engineering', 'Pre-Sales'] },
    ],
  },
  {
    slug: 'finance',
    name: 'Finance',
    blurb: 'Markets, capital, books and the technology reshaping all three.',
    niches: [
      { slug: 'investment-banking', name: 'Investment Banking', group: 'finance', aliases: ['IB', 'M&A Advisory'] },
      { slug: 'asset-management', name: 'Asset Management', group: 'finance', aliases: ['Portfolio Management', 'Wealth Management'] },
      { slug: 'hedge-funds', name: 'Hedge Funds', group: 'finance', aliases: ['Buy Side'] },
      { slug: 'quantitative-finance', name: 'Quantitative Finance', group: 'finance', aliases: ['Quant', 'Quant Trading', 'Quant Research'] },
      { slug: 'equity-research', name: 'Equity Research', group: 'finance', aliases: ['Sell Side Research'] },
      { slug: 'corporate-finance', name: 'Corporate Finance', group: 'finance', aliases: ['FP&A', 'Treasury'] },
      { slug: 'accounting', name: 'Accounting', group: 'finance', aliases: ['Audit', 'Tax', 'Controller'] },
      { slug: 'fintech', name: 'FinTech', group: 'finance', aliases: ['Financial Technology', 'Payments'] },
      { slug: 'insurance', name: 'Insurance', group: 'finance', aliases: ['InsurTech', 'Actuarial'] },
    ],
  },
  {
    slug: 'science',
    name: 'Science',
    blurb: 'Research, at the bench and on the whiteboard.',
    niches: [
      { slug: 'physics', name: 'Physics', group: 'science' },
      { slug: 'chemistry', name: 'Chemistry', group: 'science' },
      { slug: 'biology', name: 'Biology', group: 'science', aliases: ['Life Sciences'] },
      { slug: 'mathematics', name: 'Mathematics', group: 'science', aliases: ['Maths', 'Statistics'] },
      { slug: 'neuroscience', name: 'Neuroscience', group: 'science' },
      { slug: 'biotechnology', name: 'Biotechnology', group: 'science', aliases: ['Biotech', 'Synthetic Biology'] },
      { slug: 'biomedical-research', name: 'Biomedical Research', group: 'science' },
      { slug: 'materials-science', name: 'Materials Science', group: 'science' },
      { slug: 'climate-science', name: 'Climate Science', group: 'science', aliases: ['Environmental Science'] },
    ],
  },
  {
    slug: 'healthcare',
    name: 'Healthcare',
    blurb: 'Clinicians, and the people building what they use.',
    niches: [
      { slug: 'medicine', name: 'Medicine', group: 'healthcare', aliases: ['Physician', 'Surgery', 'Clinical Practice'] },
      { slug: 'dentistry', name: 'Dentistry', group: 'healthcare' },
      { slug: 'nursing', name: 'Nursing', group: 'healthcare' },
      { slug: 'pharmacy', name: 'Pharmacy', group: 'healthcare', aliases: ['Pharmaceuticals', 'Pharma'] },
      { slug: 'healthcare-technology', name: 'Healthcare Technology', group: 'healthcare', aliases: ['HealthTech', 'Digital Health'] },
      { slug: 'medical-research', name: 'Medical Research', group: 'healthcare', aliases: ['Clinical Research', 'Clinical Trials'] },
      { slug: 'health-management', name: 'Health Management', group: 'healthcare', aliases: ['Hospital Administration', 'Medical Affairs'] },
    ],
  },
  {
    slug: 'media-creative',
    name: 'Media & Creative',
    blurb: 'Storytellers, and the crews and platforms behind them.',
    niches: [
      { slug: 'film', name: 'Film', group: 'media-creative', aliases: ['Cinema', 'Directing', 'Producing'] },
      { slug: 'television', name: 'Television', group: 'media-creative', aliases: ['TV', 'Streaming'] },
      { slug: 'journalism', name: 'Journalism', group: 'media-creative', aliases: ['Reporting', 'News'] },
      { slug: 'writing', name: 'Writing', group: 'media-creative', aliases: ['Copywriting', 'Editing', 'Technical Writing'] },
      { slug: 'scriptwriting', name: 'Scriptwriting', group: 'media-creative', aliases: ['Screenwriting'] },
      { slug: 'music', name: 'Music', group: 'media-creative', aliases: ['Music Production', 'Sound Design'] },
      { slug: 'photography', name: 'Photography', group: 'media-creative' },
      { slug: 'video', name: 'Video', group: 'media-creative', aliases: ['Videography', 'Video Editing', 'Cinematography'] },
      { slug: 'animation', name: 'Animation', group: 'media-creative', aliases: ['3D Art', 'Motion Design', 'VFX'] },
      { slug: 'content-creation', name: 'Content Creation', group: 'media-creative', aliases: ['Creator', 'Influencer'] },
      { slug: 'youtube', name: 'YouTube', group: 'media-creative', aliases: ['YouTuber'] },
      { slug: 'podcasting', name: 'Podcasting', group: 'media-creative', aliases: ['Podcaster', 'Audio'] },
      { slug: 'publishing', name: 'Publishing', group: 'media-creative', aliases: ['Books', 'Editorial'] },
    ],
  },
  {
    slug: 'law-policy',
    name: 'Law & Policy',
    blurb: 'Counsel, regulators and the people shaping the rules.',
    niches: [
      { slug: 'corporate-law', name: 'Corporate Law', group: 'law-policy', aliases: ['Corporate Counsel', 'General Counsel', 'Securities Law'] },
      { slug: 'litigation', name: 'Litigation', group: 'law-policy', aliases: ['Disputes', 'Trial Law'] },
      { slug: 'intellectual-property', name: 'Intellectual Property', group: 'law-policy', aliases: ['IP', 'Patents', 'Trademarks'] },
      { slug: 'privacy-law', name: 'Privacy Law', group: 'law-policy', aliases: ['Data Protection', 'GDPR', 'DPO'] },
      { slug: 'compliance', name: 'Compliance', group: 'law-policy', aliases: ['Regulatory Affairs', 'Risk'] },
      { slug: 'public-policy', name: 'Public Policy', group: 'law-policy', aliases: ['Policy', 'Government Affairs'] },
      { slug: 'government', name: 'Government', group: 'law-policy', aliases: ['Civil Service', 'Public Sector'] },
      { slug: 'international-relations', name: 'International Relations', group: 'law-policy', aliases: ['Diplomacy', 'Foreign Affairs'] },
    ],
  },
  {
    slug: 'education',
    name: 'Education',
    blurb: 'Teaching, research and the platforms that scale both.',
    niches: [
      { slug: 'higher-education', name: 'Higher Education', group: 'education', aliases: ['University', 'Academia'] },
      { slug: 'teaching', name: 'Teaching', group: 'education', aliases: ['K-12', 'Schools', 'Tutoring'] },
      { slug: 'edtech', name: 'EdTech', group: 'education', aliases: ['Education Technology'] },
      { slug: 'academic-research', name: 'Academic Research', group: 'education', aliases: ['Postdoc', 'PhD Research'] },
      { slug: 'online-education', name: 'Online Education', group: 'education', aliases: ['Course Creation', 'Instructional Design', 'L&D'] },
    ],
  },
  {
    slug: 'engineering',
    name: 'Engineering',
    blurb: 'Engineering that ends in something physical.',
    niches: [
      { slug: 'mechanical-engineering', name: 'Mechanical Engineering', group: 'engineering' },
      { slug: 'electrical-engineering', name: 'Electrical Engineering', group: 'engineering' },
      { slug: 'electronics-engineering', name: 'Electronics Engineering', group: 'engineering', aliases: ['PCB', 'RF'] },
      { slug: 'civil-engineering', name: 'Civil Engineering', group: 'engineering', aliases: ['Structural Engineering'] },
      { slug: 'chemical-engineering', name: 'Chemical Engineering', group: 'engineering', aliases: ['Process Engineering'] },
      { slug: 'aerospace-engineering', name: 'Aerospace Engineering', group: 'engineering', aliases: ['Aviation', 'Space'] },
      { slug: 'automotive-engineering', name: 'Automotive Engineering', group: 'engineering', aliases: ['EV', 'Automotive'] },
      { slug: 'industrial-engineering', name: 'Industrial Engineering', group: 'engineering', aliases: ['Production Engineering'] },
      { slug: 'manufacturing', name: 'Manufacturing', group: 'engineering', aliases: ['Factory', 'Plant Operations'] },
      { slug: 'construction', name: 'Construction', group: 'engineering', aliases: ['Site Engineering', 'Quantity Surveying'] },
      { slug: 'architecture', name: 'Architecture', group: 'engineering', aliases: ['Urban Planning', 'Interior Design', 'Landscape Architecture'] },
    ],
  },
  {
    slug: 'consumer',
    name: 'Consumer',
    blurb: 'Brands and businesses people actually spend their evenings with.',
    niches: [
      { slug: 'fashion', name: 'Fashion', group: 'consumer', aliases: ['Apparel'] },
      { slug: 'beauty', name: 'Beauty', group: 'consumer', aliases: ['Cosmetics', 'Skincare'] },
      { slug: 'food-beverage', name: 'Food & Beverage', group: 'consumer', aliases: ['F&B', 'CPG', 'FMCG'] },
      { slug: 'restaurants', name: 'Restaurants', group: 'consumer', aliases: ['Hospitality Venues', 'Culinary'] },
      { slug: 'fitness', name: 'Fitness', group: 'consumer', aliases: ['Wellness', 'Gyms'] },
      { slug: 'sports', name: 'Sports', group: 'consumer', aliases: ['Athletics', 'Sports Business'] },
      { slug: 'travel', name: 'Travel', group: 'consumer', aliases: ['Tourism'] },
      { slug: 'hospitality', name: 'Hospitality', group: 'consumer', aliases: ['Hotels'] },
      { slug: 'luxury', name: 'Luxury', group: 'consumer', aliases: ['Premium Brands'] },
      { slug: 'e-commerce', name: 'E-commerce', group: 'consumer', aliases: ['D2C', 'Online Retail', 'Marketplace'] },
      { slug: 'consumer-brands', name: 'Consumer Brands', group: 'consumer', aliases: ['Retail'] },
    ],
  },
  {
    slug: 'real-estate',
    name: 'Real Estate',
    blurb: 'Property — buying it, building it, running it.',
    niches: [
      { slug: 'real-estate-investing', name: 'Real Estate Investing', group: 'real-estate', aliases: ['REIT', 'Property Investment'] },
      { slug: 'real-estate-development', name: 'Real Estate Development', group: 'real-estate', aliases: ['Developer'] },
      { slug: 'commercial-real-estate', name: 'Commercial Real Estate', group: 'real-estate', aliases: ['CRE', 'Office', 'Industrial Property'] },
      { slug: 'residential-real-estate', name: 'Residential Real Estate', group: 'real-estate', aliases: ['Housing', 'Brokerage'] },
      { slug: 'property-management', name: 'Property Management', group: 'real-estate', aliases: ['Facilities', 'Asset Management (Property)'] },
    ],
  },
  {
    slug: 'other',
    name: 'Industry & Infrastructure',
    blurb: 'The sectors that move atoms, electrons and everything else.',
    niches: [
      { slug: 'agriculture', name: 'Agriculture', group: 'other', aliases: ['AgTech', 'Farming'] },
      { slug: 'energy', name: 'Energy', group: 'other', aliases: ['Oil & Gas', 'Utilities'] },
      { slug: 'renewable-energy', name: 'Renewable Energy', group: 'other', aliases: ['Solar', 'Wind', 'CleanTech'] },
      { slug: 'transportation', name: 'Transportation', group: 'other', aliases: ['Mobility', 'Rail', 'Aviation Ops'] },
      { slug: 'logistics', name: 'Logistics', group: 'other', aliases: ['Supply Chain', 'Freight', 'Warehousing'] },
      { slug: 'telecommunications', name: 'Telecommunications', group: 'other', aliases: ['Telecom', 'Networks'] },
      { slug: 'defence', name: 'Defence', group: 'other', aliases: ['Defense', 'Military', 'Aerospace & Defence'] },
      { slug: 'nonprofits', name: 'Nonprofits', group: 'other', aliases: ['NGO', 'Social Impact', 'Philanthropy'] },
      { slug: 'sustainability', name: 'Sustainability', group: 'other', aliases: ['ESG', 'Climate'] },
    ],
  },
]

export const NICHES = NICHE_GROUPS.flatMap((g) => g.niches)

export const NICHE_BY_SLUG = new Map(NICHES.map((n) => [n.slug, n]))

export const NICHE_GROUP_BY_SLUG = new Map(NICHE_GROUPS.map((g) => [g.slug, g]))
