import type { RoleFamily } from './types'

/**
 * Roles — the specific job, with seniority stripped out.
 *
 * Following the rule that seniority is its own dimension, this list holds no
 * "Senior X" / "VP of X" / "Head of X" entries. Those are the same role at a
 * different level, and `normalizeTitle()` splits them apart. What *does* earn a
 * separate row is a genuine specialisation: a Backend Engineer and an iOS
 * Engineer do different work at every level.
 *
 * Each family declares the niches it usually maps to, best match first, so the
 * application form can suggest a niche from a job title.
 */
export const ROLE_FAMILIES: RoleFamily[] = [
  {
    slug: 'software-engineering',
    name: 'Engineering & Software',
    niches: ['software-engineering', 'web-development', 'mobile-development', 'devops', 'cloud-computing'],
    roles: [
      { slug: 'software-engineer', name: 'Software Engineer', family: 'software-engineering', aliases: ['Software Developer', 'SDE', 'Programmer', 'Software Development Engineer'] },
      { slug: 'full-stack-engineer', name: 'Full-Stack Engineer', family: 'software-engineering', niche: 'web-development', aliases: ['Full Stack Developer', 'Fullstack Engineer'] },
      { slug: 'frontend-engineer', name: 'Frontend Engineer', family: 'software-engineering', niche: 'web-development', aliases: ['Front-End Developer', 'UI Engineer', 'React Developer', 'JavaScript Developer', 'TypeScript Developer'] },
      { slug: 'backend-engineer', name: 'Backend Engineer', family: 'software-engineering', aliases: ['Back-End Developer', 'Server Engineer'] },
      { slug: 'web-developer', name: 'Web Developer', family: 'software-engineering', niche: 'web-development', aliases: ['PHP Developer', 'Ruby Developer', 'Wordpress Developer'] },
      { slug: 'mobile-engineer', name: 'Mobile Engineer', family: 'software-engineering', niche: 'mobile-development', aliases: ['Mobile Developer', 'React Native Developer', 'Flutter Developer'] },
      { slug: 'ios-engineer', name: 'iOS Engineer', family: 'software-engineering', niche: 'mobile-development', aliases: ['iOS Developer', 'Swift Developer'] },
      { slug: 'android-engineer', name: 'Android Engineer', family: 'software-engineering', niche: 'mobile-development', aliases: ['Android Developer', 'Kotlin Developer'] },
      { slug: 'devops-engineer', name: 'DevOps Engineer', family: 'software-engineering', niche: 'devops', aliases: ['Build Engineer', 'Release Engineer'] },
      { slug: 'platform-engineer', name: 'Platform Engineer', family: 'software-engineering', niche: 'devops', aliases: ['Developer Platform Engineer'] },
      { slug: 'infrastructure-engineer', name: 'Infrastructure Engineer', family: 'software-engineering', niche: 'devops', aliases: ['Systems Engineer'] },
      { slug: 'cloud-engineer', name: 'Cloud Engineer', family: 'software-engineering', niche: 'cloud-computing', aliases: ['AWS Engineer', 'Azure Engineer', 'GCP Engineer'] },
      { slug: 'site-reliability-engineer', name: 'Site Reliability Engineer', family: 'software-engineering', niche: 'devops', aliases: ['SRE', 'Reliability Engineer'] },
      { slug: 'network-engineer', name: 'Network Engineer', family: 'software-engineering', niche: 'devops', aliases: ['Network Administrator'] },
      { slug: 'database-engineer', name: 'Database Engineer', family: 'software-engineering', aliases: ['Database Administrator', 'DBA'] },
      { slug: 'api-engineer', name: 'API Engineer', family: 'software-engineering', aliases: ['Integration Engineer'] },
      { slug: 'embedded-engineer', name: 'Embedded Engineer', family: 'software-engineering', niche: 'hardware', aliases: ['Firmware Engineer', 'Embedded Systems Engineer'] },
      { slug: 'qa-engineer', name: 'QA Engineer', family: 'software-engineering', aliases: ['Test Engineer', 'Quality Engineer', 'SDET', 'Automation Engineer'] },
      { slug: 'performance-engineer', name: 'Performance Engineer', family: 'software-engineering' },
      { slug: 'solutions-engineer', name: 'Solutions Engineer', family: 'software-engineering', aliases: ['Sales Engineer', 'Solutions Consultant', 'Pre-Sales Engineer'] },
      { slug: 'support-engineer', name: 'Support Engineer', family: 'software-engineering', aliases: ['Technical Support Engineer'] },
      { slug: 'developer-advocate', name: 'Developer Advocate', family: 'software-engineering', aliases: ['Developer Relations', 'DevRel', 'Developer Evangelist'] },
      { slug: 'technical-writer', name: 'Technical Writer', family: 'software-engineering', niche: 'writing', aliases: ['Documentation Engineer'] },
      { slug: 'engineering-manager', name: 'Engineering Manager', family: 'software-engineering', aliases: ['EM'] },
    ],
  },
  {
    slug: 'ai-ml',
    name: 'AI & Machine Learning',
    niches: ['ai', 'machine-learning', 'data-science', 'robotics'],
    roles: [
      { slug: 'ai-engineer', name: 'AI Engineer', family: 'ai-ml', aliases: ['Generative AI Engineer', 'AI Application Engineer', 'AI Product Engineer'] },
      { slug: 'machine-learning-engineer', name: 'Machine Learning Engineer', family: 'ai-ml', niche: 'machine-learning', aliases: ['ML Engineer', 'MLE'] },
      { slug: 'deep-learning-engineer', name: 'Deep Learning Engineer', family: 'ai-ml', niche: 'machine-learning' },
      { slug: 'llm-engineer', name: 'LLM Engineer', family: 'ai-ml', aliases: ['Large Language Model Engineer', 'Foundation Model Engineer'] },
      { slug: 'nlp-engineer', name: 'NLP Engineer', family: 'ai-ml', aliases: ['Natural Language Processing Engineer'] },
      { slug: 'computer-vision-engineer', name: 'Computer Vision Engineer', family: 'ai-ml', aliases: ['CV Engineer', 'Vision Engineer'] },
      { slug: 'speech-ai-engineer', name: 'Speech AI Engineer', family: 'ai-ml', aliases: ['Speech Recognition Engineer', 'Audio ML Engineer'] },
      { slug: 'reinforcement-learning-engineer', name: 'Reinforcement Learning Engineer', family: 'ai-ml', aliases: ['RL Engineer'] },
      { slug: 'mlops-engineer', name: 'MLOps Engineer', family: 'ai-ml', niche: 'machine-learning', aliases: ['ML Infrastructure Engineer', 'ML Platform Engineer'] },
      { slug: 'ai-infrastructure-engineer', name: 'AI Infrastructure Engineer', family: 'ai-ml', aliases: ['AI Platform Engineer'] },
      { slug: 'ai-architect', name: 'AI Architect', family: 'ai-ml', aliases: ['AI Solutions Architect'] },
      { slug: 'ai-researcher', name: 'AI Researcher', family: 'ai-ml', aliases: ['AI Scientist', 'ML Researcher', 'LLM Researcher', 'Deep Learning Researcher'] },
      { slug: 'research-scientist', name: 'Research Scientist', family: 'ai-ml', aliases: ['Applied Scientist', 'Member of Technical Staff'] },
      { slug: 'research-engineer', name: 'Research Engineer', family: 'ai-ml' },
      { slug: 'ai-safety-researcher', name: 'AI Safety Researcher', family: 'ai-ml', aliases: ['AI Alignment Researcher', 'AI Red Team Engineer'] },
      { slug: 'ai-evaluation-engineer', name: 'AI Evaluation Engineer', family: 'ai-ml', aliases: ['Evals Engineer', 'AI Quality Engineer'] },
      { slug: 'prompt-engineer', name: 'Prompt Engineer', family: 'ai-ml', aliases: ['AI Trainer', 'AI Data Specialist'] },
      { slug: 'robotics-engineer', name: 'Robotics Engineer', family: 'ai-ml', niche: 'robotics', aliases: ['Autonomous Systems Engineer'] },
      { slug: 'ai-product-manager', name: 'AI Product Manager', family: 'ai-ml', aliases: ['AI PM'] },
      { slug: 'ai-consultant', name: 'AI Consultant', family: 'ai-ml', aliases: ['AI Strategist'] },
    ],
  },
  {
    slug: 'data',
    name: 'Data',
    niches: ['data-science', 'machine-learning', 'software-engineering'],
    roles: [
      { slug: 'data-scientist', name: 'Data Scientist', family: 'data', aliases: ['DS'] },
      { slug: 'data-analyst', name: 'Data Analyst', family: 'data', aliases: ['Database Analyst', 'Data Quality Analyst'] },
      { slug: 'business-analyst', name: 'Business Analyst', family: 'data', aliases: ['BA'] },
      { slug: 'data-engineer', name: 'Data Engineer', family: 'data', aliases: ['Data Platform Engineer', 'Data Infrastructure Engineer', 'Data Warehouse Engineer'] },
      { slug: 'analytics-engineer', name: 'Analytics Engineer', family: 'data', aliases: ['dbt Engineer'] },
      { slug: 'bi-analyst', name: 'BI Analyst', family: 'data', aliases: ['Business Intelligence Analyst', 'BI Developer', 'Business Intelligence Engineer'] },
      { slug: 'data-architect', name: 'Data Architect', family: 'data' },
      { slug: 'data-governance-specialist', name: 'Data Governance Specialist', family: 'data' },
      { slug: 'data-visualization-specialist', name: 'Data Visualisation Specialist', family: 'data', aliases: ['Data Visualization Specialist', 'Tableau Developer'] },
      { slug: 'quantitative-analyst', name: 'Quantitative Analyst', family: 'data', niche: 'quantitative-finance', aliases: ['Quant Analyst', 'Quant'] },
      { slug: 'statistician', name: 'Statistician', family: 'data', aliases: ['Biostatistician'] },
      { slug: 'operations-research-analyst', name: 'Operations Research Analyst', family: 'data' },
      { slug: 'data-product-manager', name: 'Data Product Manager', family: 'data' },
    ],
  },
  {
    slug: 'product',
    name: 'Product',
    niches: ['product-management'],
    roles: [
      { slug: 'product-manager', name: 'Product Manager', family: 'product', aliases: ['PM', 'Product Owner', 'Product Lead'] },
      { slug: 'technical-product-manager', name: 'Technical Product Manager', family: 'product', aliases: ['TPM'] },
      { slug: 'growth-product-manager', name: 'Growth Product Manager', family: 'product' },
      { slug: 'platform-product-manager', name: 'Platform Product Manager', family: 'product' },
      { slug: 'product-operations', name: 'Product Operations', family: 'product', aliases: ['Product Ops'] },
      { slug: 'product-analyst', name: 'Product Analyst', family: 'product' },
      { slug: 'product-strategist', name: 'Product Strategist', family: 'product' },
      { slug: 'program-manager', name: 'Program Manager', family: 'product', aliases: ['Technical Program Manager', 'TPgM', 'Programme Manager'] },
      { slug: 'project-manager', name: 'Project Manager', family: 'product', aliases: ['Project Coordinator', 'Delivery Manager', 'Scrum Master'] },
    ],
  },
  {
    slug: 'design',
    name: 'Design',
    niches: ['product-design', 'ux', 'ui', 'graphic-design', 'branding', 'industrial-design'],
    roles: [
      { slug: 'product-designer', name: 'Product Designer', family: 'design', aliases: ['UX/UI Designer'] },
      { slug: 'ux-designer', name: 'UX Designer', family: 'design', niche: 'ux', aliases: ['User Experience Designer', 'Interaction Designer'] },
      { slug: 'ui-designer', name: 'UI Designer', family: 'design', niche: 'ui', aliases: ['User Interface Designer', 'Visual Designer'] },
      { slug: 'ux-researcher', name: 'UX Researcher', family: 'design', niche: 'ux-research', aliases: ['User Researcher', 'Design Researcher'] },
      { slug: 'graphic-designer', name: 'Graphic Designer', family: 'design', niche: 'graphic-design' },
      { slug: 'brand-designer', name: 'Brand Designer', family: 'design', niche: 'branding', aliases: ['Brand Strategist', 'Identity Designer'] },
      { slug: 'motion-designer', name: 'Motion Designer', family: 'design', niche: 'animation', aliases: ['Motion Graphics Designer'] },
      { slug: '3d-designer', name: '3D Designer', family: 'design', niche: 'animation', aliases: ['3D Artist'] },
      { slug: 'industrial-designer', name: 'Industrial Designer', family: 'design', niche: 'industrial-design' },
      { slug: 'service-designer', name: 'Service Designer', family: 'design' },
      { slug: 'design-engineer', name: 'Design Engineer', family: 'design', aliases: ['Creative Technologist', 'Design Systems Engineer'] },
      { slug: 'design-systems-designer', name: 'Design Systems Designer', family: 'design' },
      { slug: 'art-director', name: 'Art Director', family: 'design', niche: 'graphic-design' },
      { slug: 'creative-director', name: 'Creative Director', family: 'design', niche: 'branding' },
    ],
  },
  {
    slug: 'growth',
    name: 'Growth',
    niches: ['growth', 'growth-engineering', 'performance-marketing'],
    roles: [
      { slug: 'growth-manager', name: 'Growth Manager', family: 'growth', aliases: ['Growth Lead', 'Growth Hacker', 'Growth Marketing Manager'] },
      { slug: 'growth-engineer', name: 'Growth Engineer', family: 'growth' },
      { slug: 'growth-analyst', name: 'Growth Analyst', family: 'growth' },
      { slug: 'growth-strategist', name: 'Growth Strategist', family: 'growth' },
      { slug: 'user-acquisition-manager', name: 'User Acquisition Manager', family: 'growth', aliases: ['Acquisition Manager', 'UA Manager'] },
      { slug: 'performance-marketing-manager', name: 'Performance Marketing Manager', family: 'growth', aliases: ['Performance Marketer', 'Paid Media Manager'] },
      { slug: 'cro-specialist', name: 'Conversion Rate Optimisation Specialist', family: 'growth', aliases: ['CRO Specialist', 'Conversion Rate Optimization Specialist'] },
      { slug: 'lifecycle-marketing-manager', name: 'Lifecycle Marketing Manager', family: 'growth', aliases: ['Retention Manager', 'Engagement Manager', 'CRM Manager'] },
      { slug: 'marketing-operations', name: 'Marketing Operations', family: 'growth', aliases: ['Marketing Ops', 'MOps'] },
      { slug: 'revenue-operations', name: 'Revenue Operations', family: 'growth', aliases: ['RevOps'] },
    ],
  },
  {
    slug: 'marketing',
    name: 'Marketing',
    niches: ['brand-marketing', 'content-marketing', 'product-marketing', 'seo', 'social-media', 'advertising', 'public-relations', 'community', 'influencer-marketing'],
    roles: [
      { slug: 'marketing-manager', name: 'Marketing Manager', family: 'marketing', aliases: ['Marketing Executive', 'Marketing Specialist', 'Digital Marketing Manager'] },
      { slug: 'product-marketing-manager', name: 'Product Marketing Manager', family: 'marketing', niche: 'product-marketing', aliases: ['PMM'] },
      { slug: 'content-marketing-manager', name: 'Content Marketing Manager', family: 'marketing', niche: 'content-marketing', aliases: ['Content Strategist'] },
      { slug: 'content-writer', name: 'Content Writer', family: 'marketing', niche: 'content-marketing', aliases: ['Copywriter', 'Content Marketer'] },
      { slug: 'seo-specialist', name: 'SEO Specialist', family: 'marketing', niche: 'seo', aliases: ['SEO Manager', 'Search Marketing Manager'] },
      { slug: 'sem-specialist', name: 'SEM Specialist', family: 'marketing', niche: 'performance-marketing', aliases: ['Paid Search Specialist', 'PPC Specialist'] },
      { slug: 'social-media-manager', name: 'Social Media Manager', family: 'marketing', niche: 'social-media', aliases: ['Social Media Strategist'] },
      { slug: 'community-manager', name: 'Community Manager', family: 'marketing', niche: 'community', aliases: ['Community Lead'] },
      { slug: 'influencer-marketing-manager', name: 'Influencer Marketing Manager', family: 'marketing', niche: 'influencer-marketing', aliases: ['Creator Partnerships Manager'] },
      { slug: 'affiliate-marketing-manager', name: 'Affiliate Marketing Manager', family: 'marketing', niche: 'performance-marketing' },
      { slug: 'email-marketing-manager', name: 'Email Marketing Manager', family: 'marketing', niche: 'content-marketing' },
      { slug: 'brand-manager', name: 'Brand Manager', family: 'marketing' },
      { slug: 'communications-manager', name: 'Communications Manager', family: 'marketing', niche: 'public-relations', aliases: ['Corporate Communications'] },
      { slug: 'pr-manager', name: 'PR Manager', family: 'marketing', niche: 'public-relations', aliases: ['Public Relations Specialist', 'Publicist'] },
      { slug: 'events-manager', name: 'Events Manager', family: 'marketing', aliases: ['Field Marketing Manager'] },
      { slug: 'marketing-analyst', name: 'Marketing Analyst', family: 'marketing' },
      { slug: 'demand-generation-manager', name: 'Demand Generation Manager', family: 'marketing', niche: 'performance-marketing', aliases: ['Demand Gen Manager'] },
    ],
  },
  {
    slug: 'sales',
    name: 'Sales',
    niches: ['sales', 'enterprise-sales', 'business-development', 'partnerships', 'account-management', 'sales-engineering'],
    roles: [
      { slug: 'account-executive', name: 'Account Executive', family: 'sales', aliases: ['AE', 'Enterprise Account Executive', 'SMB Account Executive'] },
      { slug: 'sales-representative', name: 'Sales Representative', family: 'sales', aliases: ['Sales Executive', 'Inside Sales', 'Field Sales'] },
      { slug: 'sales-development-representative', name: 'Sales Development Representative', family: 'sales', aliases: ['SDR', 'BDR', 'Business Development Representative'] },
      { slug: 'account-manager', name: 'Account Manager', family: 'sales', aliases: ['Key Account Manager', 'Client Partner'] },
      { slug: 'sales-operations', name: 'Sales Operations', family: 'sales', aliases: ['Sales Ops', 'Sales Enablement'] },
      { slug: 'sales-analyst', name: 'Sales Analyst', family: 'sales' },
      { slug: 'partnerships-manager', name: 'Partnerships Manager', family: 'sales', aliases: ['Channel Manager', 'Strategic Partnerships', 'Alliances Manager'] },
      { slug: 'business-development-manager', name: 'Business Development Manager', family: 'sales', aliases: ['BD Manager'] },
    ],
  },
  {
    slug: 'customer',
    name: 'Customer & Support',
    niches: ['account-management', 'sales'],
    roles: [
      { slug: 'customer-success-manager', name: 'Customer Success Manager', family: 'customer', aliases: ['CSM', 'Customer Success Associate', 'Customer Success Lead'] },
      { slug: 'customer-support-representative', name: 'Customer Support Representative', family: 'customer', aliases: ['Customer Service Representative', 'Support Specialist'] },
      { slug: 'customer-experience-manager', name: 'Customer Experience Manager', family: 'customer', aliases: ['CX Manager', 'Customer Experience Specialist'] },
      { slug: 'implementation-specialist', name: 'Implementation Specialist', family: 'customer', aliases: ['Implementation Manager', 'Onboarding Specialist'] },
      { slug: 'customer-operations', name: 'Customer Operations', family: 'customer', aliases: ['Customer Success Operations', 'Support Operations'] },
      { slug: 'customer-insights-analyst', name: 'Customer Insights Analyst', family: 'customer' },
    ],
  },
  {
    slug: 'operations',
    name: 'Operations',
    niches: ['operations', 'strategy', 'logistics'],
    roles: [
      { slug: 'operations-manager', name: 'Operations Manager', family: 'operations', aliases: ['Ops Manager'] },
      { slug: 'operations-analyst', name: 'Operations Analyst', family: 'operations' },
      { slug: 'business-operations', name: 'Business Operations', family: 'operations', aliases: ['BizOps', 'Strategy & Operations'] },
      { slug: 'people-operations', name: 'People Operations', family: 'operations', aliases: ['People Ops'] },
      { slug: 'supply-chain-manager', name: 'Supply Chain Manager', family: 'operations', aliases: ['Supply Chain Operations'] },
      { slug: 'logistics-manager', name: 'Logistics Manager', family: 'operations', aliases: ['Logistics Operations', 'Warehouse Manager'] },
      { slug: 'procurement-manager', name: 'Procurement Manager', family: 'operations', aliases: ['Procurement Operations', 'Sourcing Manager'] },
      { slug: 'process-improvement-manager', name: 'Process Improvement Manager', family: 'operations', aliases: ['Continuous Improvement Manager'] },
      { slug: 'chief-of-staff', name: 'Chief of Staff', family: 'operations', aliases: ['CoS'] },
    ],
  },
  {
    slug: 'finance',
    name: 'Finance',
    niches: ['corporate-finance', 'accounting', 'fintech', 'insurance'],
    roles: [
      { slug: 'accountant', name: 'Accountant', family: 'finance', niche: 'accounting', aliases: ['Chartered Accountant', 'CPA', 'Accounting Manager'] },
      { slug: 'financial-analyst', name: 'Financial Analyst', family: 'finance', aliases: ['Finance Analyst', 'FP&A Analyst', 'FP&A Manager'] },
      { slug: 'credit-analyst', name: 'Credit Analyst', family: 'finance' },
      { slug: 'risk-analyst', name: 'Risk Analyst', family: 'finance', aliases: ['Risk Manager'] },
      { slug: 'treasury-analyst', name: 'Treasury Analyst', family: 'finance' },
      { slug: 'tax-specialist', name: 'Tax Specialist', family: 'finance', niche: 'accounting', aliases: ['Tax Manager', 'Tax Consultant'] },
      { slug: 'auditor', name: 'Auditor', family: 'finance', niche: 'accounting', aliases: ['Internal Auditor', 'External Auditor'] },
      { slug: 'controller', name: 'Controller', family: 'finance', niche: 'accounting', aliases: ['Financial Controller'] },
      { slug: 'finance-manager', name: 'Finance Manager', family: 'finance' },
      { slug: 'actuary', name: 'Actuary', family: 'finance', niche: 'insurance', aliases: ['Actuarial Analyst'] },
    ],
  },
  {
    slug: 'investing',
    name: 'Investing & Capital Markets',
    niches: ['venture-capital', 'private-equity', 'investing', 'investment-banking', 'hedge-funds', 'quantitative-finance', 'equity-research', 'asset-management'],
    roles: [
      { slug: 'venture-capital-investor', name: 'Venture Capital Investor', family: 'investing', aliases: ['VC Analyst', 'VC Associate', 'VC Principal', 'VC Partner', 'Venture Capitalist'] },
      { slug: 'private-equity-investor', name: 'Private Equity Investor', family: 'investing', niche: 'private-equity', aliases: ['PE Analyst', 'PE Associate', 'PE Principal', 'Private Equity Associate'] },
      { slug: 'investment-analyst', name: 'Investment Analyst', family: 'investing', niche: 'investing', aliases: ['Investment Associate', 'Investment Manager'] },
      { slug: 'portfolio-manager', name: 'Portfolio Manager', family: 'investing', niche: 'asset-management', aliases: ['PM (Investing)'] },
      { slug: 'hedge-fund-analyst', name: 'Hedge Fund Analyst', family: 'investing', niche: 'hedge-funds', aliases: ['Buy Side Analyst'] },
      { slug: 'equity-research-analyst', name: 'Equity Research Analyst', family: 'investing', niche: 'equity-research', aliases: ['Research Analyst (Equities)', 'Sell Side Analyst'] },
      { slug: 'quantitative-researcher', name: 'Quantitative Researcher', family: 'investing', niche: 'quantitative-finance', aliases: ['Quant Researcher'] },
      { slug: 'trader', name: 'Trader', family: 'investing', niche: 'quantitative-finance', aliases: ['Quant Trader', 'Prop Trader', 'Execution Trader'] },
      { slug: 'investment-banker', name: 'Investment Banker', family: 'investing', niche: 'investment-banking', aliases: ['M&A Analyst', 'M&A Associate', 'IB Analyst'] },
      { slug: 'corporate-development-manager', name: 'Corporate Development Manager', family: 'investing', niche: 'corporate-development', aliases: ['Corp Dev', 'Corporate Venture Capital'] },
      { slug: 'angel-investor', name: 'Angel Investor', family: 'investing', niche: 'investing', aliases: ['Family Office Investment Manager', 'LP'] },
    ],
  },
  {
    slug: 'people',
    name: 'HR & People',
    niches: ['operations', 'startups'],
    roles: [
      { slug: 'recruiter', name: 'Recruiter', family: 'people', aliases: ['Technical Recruiter', 'Executive Recruiter', 'Talent Acquisition Specialist', 'Talent Acquisition Manager', 'Sourcer'] },
      { slug: 'hr-generalist', name: 'HR Generalist', family: 'people', aliases: ['HR Business Partner', 'HRBP', 'People Partner'] },
      { slug: 'people-analytics', name: 'People Analytics', family: 'people' },
      { slug: 'compensation-analyst', name: 'Compensation Analyst', family: 'people', aliases: ['Compensation & Benefits Manager', 'Total Rewards'] },
      { slug: 'learning-development', name: 'Learning & Development', family: 'people', aliases: ['L&D', 'Training Manager', 'Corporate Trainer', 'Talent Development'] },
      { slug: 'employee-relations', name: 'Employee Relations', family: 'people', aliases: ['People Experience'] },
    ],
  },
  {
    slug: 'legal',
    name: 'Legal & Compliance',
    niches: ['corporate-law', 'litigation', 'intellectual-property', 'privacy-law', 'compliance'],
    roles: [
      { slug: 'lawyer', name: 'Lawyer', family: 'legal', aliases: ['Attorney', 'Advocate', 'Solicitor', 'Barrister'] },
      { slug: 'corporate-counsel', name: 'Corporate Counsel', family: 'legal', aliases: ['In-House Counsel', 'Legal Counsel', 'General Counsel', 'Corporate Lawyer'] },
      { slug: 'litigation-lawyer', name: 'Litigation Lawyer', family: 'legal', niche: 'litigation', aliases: ['Trial Lawyer', 'Disputes Lawyer'] },
      { slug: 'ip-lawyer', name: 'Intellectual Property Lawyer', family: 'legal', niche: 'intellectual-property', aliases: ['Patent Attorney', 'IP Counsel', 'Trademark Attorney'] },
      { slug: 'employment-lawyer', name: 'Employment Lawyer', family: 'legal', aliases: ['Labour Lawyer'] },
      { slug: 'securities-lawyer', name: 'Securities Lawyer', family: 'legal' },
      { slug: 'privacy-counsel', name: 'Privacy Counsel', family: 'legal', niche: 'privacy-law', aliases: ['Data Protection Officer', 'DPO'] },
      { slug: 'legal-operations', name: 'Legal Operations', family: 'legal', aliases: ['Legal Ops', 'Contract Manager', 'Contract Specialist'] },
      { slug: 'compliance-analyst', name: 'Compliance Analyst', family: 'legal', niche: 'compliance', aliases: ['Compliance Manager', 'Regulatory Affairs'] },
    ],
  },
  {
    slug: 'security',
    name: 'Security',
    niches: ['cybersecurity'],
    roles: [
      { slug: 'security-engineer', name: 'Security Engineer', family: 'security', aliases: ['Application Security Engineer', 'AppSec Engineer', 'DevSecOps Engineer', 'Cloud Security Engineer', 'Network Security Engineer'] },
      { slug: 'security-analyst', name: 'Security Analyst', family: 'security', aliases: ['Cybersecurity Analyst', 'SOC Analyst'] },
      { slug: 'security-architect', name: 'Security Architect', family: 'security' },
      { slug: 'penetration-tester', name: 'Penetration Tester', family: 'security', aliases: ['Ethical Hacker', 'Red Team Engineer', 'Offensive Security Engineer'] },
      { slug: 'incident-response', name: 'Incident Response', family: 'security', aliases: ['Blue Team Engineer', 'Digital Forensics', 'DFIR'] },
      { slug: 'threat-intelligence-analyst', name: 'Threat Intelligence Analyst', family: 'security' },
      { slug: 'security-researcher', name: 'Security Researcher', family: 'security', aliases: ['Vulnerability Researcher'] },
    ],
  },
  {
    slug: 'science',
    name: 'Science & Research',
    niches: ['physics', 'chemistry', 'biology', 'mathematics', 'neuroscience', 'materials-science', 'climate-science', 'academic-research'],
    roles: [
      { slug: 'scientist', name: 'Scientist', family: 'science', niche: 'academic-research', aliases: ['Researcher'] },
      { slug: 'physicist', name: 'Physicist', family: 'science' },
      { slug: 'chemist', name: 'Chemist', family: 'science', niche: 'chemistry' },
      { slug: 'biologist', name: 'Biologist', family: 'science', niche: 'biology', aliases: ['Molecular Biologist'] },
      { slug: 'mathematician', name: 'Mathematician', family: 'science', niche: 'mathematics' },
      { slug: 'economist', name: 'Economist', family: 'science', niche: 'mathematics' },
      { slug: 'neuroscientist', name: 'Neuroscientist', family: 'science', niche: 'neuroscience' },
      { slug: 'materials-scientist', name: 'Materials Scientist', family: 'science', niche: 'materials-science' },
      { slug: 'environmental-scientist', name: 'Environmental Scientist', family: 'science', niche: 'climate-science', aliases: ['Climate Scientist'] },
      { slug: 'computational-scientist', name: 'Computational Scientist', family: 'science', niche: 'mathematics' },
      { slug: 'social-scientist', name: 'Social Scientist', family: 'science', niche: 'academic-research', aliases: ['Sociologist', 'Anthropologist'] },
      { slug: 'research-assistant', name: 'Research Assistant', family: 'science', niche: 'academic-research', aliases: ['Lab Technician', 'Postdoctoral Researcher', 'Postdoc'] },
    ],
  },
  {
    slug: 'healthcare',
    name: 'Healthcare & Medical',
    niches: ['medicine', 'dentistry', 'nursing', 'pharmacy', 'healthcare-technology', 'medical-research', 'health-management'],
    roles: [
      { slug: 'physician', name: 'Physician', family: 'healthcare', aliases: ['Doctor', 'Medical Doctor', 'MD', 'Consultant Physician'] },
      { slug: 'surgeon', name: 'Surgeon', family: 'healthcare' },
      { slug: 'radiologist', name: 'Radiologist', family: 'healthcare' },
      { slug: 'dentist', name: 'Dentist', family: 'healthcare', niche: 'dentistry' },
      { slug: 'nurse', name: 'Nurse', family: 'healthcare', niche: 'nursing', aliases: ['Registered Nurse', 'RN', 'Nurse Practitioner'] },
      { slug: 'pharmacist', name: 'Pharmacist', family: 'healthcare', niche: 'pharmacy' },
      { slug: 'physiotherapist', name: 'Physiotherapist', family: 'healthcare', aliases: ['Physical Therapist'] },
      { slug: 'psychologist', name: 'Psychologist', family: 'healthcare', aliases: ['Therapist', 'Counsellor', 'Psychiatrist'] },
      { slug: 'clinical-researcher', name: 'Clinical Researcher', family: 'healthcare', niche: 'medical-research', aliases: ['Clinical Research Associate', 'Clinical Trial Manager', 'Medical Researcher'] },
      { slug: 'biomedical-engineer', name: 'Biomedical Engineer', family: 'healthcare', niche: 'healthcare-technology', aliases: ['Medical Device Engineer'] },
      { slug: 'medical-technologist', name: 'Medical Technologist', family: 'healthcare', niche: 'healthcare-technology', aliases: ['Medical Laboratory Scientist'] },
      { slug: 'medical-affairs', name: 'Medical Affairs', family: 'healthcare', niche: 'health-management', aliases: ['Medical Science Liaison', 'MSL'] },
      { slug: 'hospital-administrator', name: 'Hospital Administrator', family: 'healthcare', niche: 'health-management', aliases: ['Healthcare Administrator'] },
    ],
  },
  {
    slug: 'media',
    name: 'Media & Creative',
    niches: ['film', 'television', 'journalism', 'writing', 'music', 'photography', 'video', 'animation', 'content-creation', 'podcasting', 'publishing'],
    roles: [
      { slug: 'writer', name: 'Writer', family: 'media', niche: 'writing', aliases: ['Author', 'Novelist'] },
      { slug: 'screenwriter', name: 'Screenwriter', family: 'media', niche: 'scriptwriting', aliases: ['Scriptwriter'] },
      { slug: 'journalist', name: 'Journalist', family: 'media', niche: 'journalism', aliases: ['Reporter', 'Correspondent', 'News Anchor'] },
      { slug: 'editor', name: 'Editor', family: 'media', niche: 'publishing', aliases: ['Commissioning Editor', 'Managing Editor'] },
      { slug: 'content-creator', name: 'Content Creator', family: 'media', niche: 'content-creation', aliases: ['YouTuber', 'Social Media Creator', 'Influencer', 'Streamer'] },
      { slug: 'podcaster', name: 'Podcaster', family: 'media', niche: 'podcasting', aliases: ['Podcast Host', 'Podcast Producer'] },
      { slug: 'producer', name: 'Producer', family: 'media', aliases: ['Film Producer', 'TV Producer', 'Line Producer'] },
      { slug: 'film-director', name: 'Film Director', family: 'media', aliases: ['Assistant Director', 'Showrunner'] },
      { slug: 'cinematographer', name: 'Cinematographer', family: 'media', aliases: ['Director of Photography', 'DoP', 'Videographer'] },
      { slug: 'video-editor', name: 'Video Editor', family: 'media', niche: 'video', aliases: ['Post-Production Editor'] },
      { slug: 'photographer', name: 'Photographer', family: 'media', niche: 'photography' },
      { slug: 'animator', name: 'Animator', family: 'media', niche: 'animation', aliases: ['VFX Artist', 'Illustrator'] },
      { slug: 'music-producer', name: 'Music Producer', family: 'media', niche: 'music', aliases: ['Sound Designer', 'Audio Engineer', 'Composer'] },
      { slug: 'voice-artist', name: 'Voice Artist', family: 'media', niche: 'music', aliases: ['Voice Actor', 'Narrator'] },
    ],
  },
  {
    slug: 'consulting',
    name: 'Consulting',
    niches: ['management-consulting', 'strategy'],
    roles: [
      { slug: 'management-consultant', name: 'Management Consultant', family: 'consulting', aliases: ['Strategy Consultant', 'Consultant', 'Consulting Analyst', 'Consulting Associate'] },
      { slug: 'technology-consultant', name: 'Technology Consultant', family: 'consulting', aliases: ['IT Consultant', 'Digital Transformation Consultant'] },
      { slug: 'data-consultant', name: 'Data Consultant', family: 'consulting', aliases: ['Analytics Consultant'] },
      { slug: 'financial-consultant', name: 'Financial Consultant', family: 'consulting', aliases: ['Finance Advisor'] },
      { slug: 'hr-consultant', name: 'HR Consultant', family: 'consulting', aliases: ['People Consultant'] },
      { slug: 'operations-consultant', name: 'Operations Consultant', family: 'consulting', aliases: ['Business Consultant'] },
      { slug: 'cybersecurity-consultant', name: 'Cybersecurity Consultant', family: 'consulting', aliases: ['Security Consultant'] },
      { slug: 'sustainability-consultant', name: 'Sustainability Consultant', family: 'consulting', aliases: ['ESG Consultant'] },
      { slug: 'healthcare-consultant', name: 'Healthcare Consultant', family: 'consulting' },
      { slug: 'marketing-consultant', name: 'Marketing Consultant', family: 'consulting' },
    ],
  },
  {
    slug: 'leadership',
    name: 'Founders & Leadership',
    niches: ['entrepreneurship', 'startups', 'strategy'],
    roles: [
      { slug: 'founder', name: 'Founder', family: 'leadership', aliases: ['Co-Founder', 'Cofounder', 'Founding Partner'] },
      { slug: 'entrepreneur', name: 'Entrepreneur', family: 'leadership', aliases: ['Solopreneur', 'Business Owner', 'Entrepreneur in Residence', 'EIR'] },
      { slug: 'chief-executive', name: 'Chief Executive', family: 'leadership', aliases: ['CEO', 'President', 'Managing Director'] },
      { slug: 'general-manager', name: 'General Manager', family: 'leadership', aliases: ['Country Manager', 'Regional Director', 'Business Unit Head'] },
      { slug: 'board-member', name: 'Board Member', family: 'leadership', aliases: ['Non-Executive Director', 'NED', 'Board Advisor'] },
      { slug: 'advisor', name: 'Advisor', family: 'leadership', aliases: ['Strategic Advisor', 'Mentor'] },
    ],
  },
  {
    slug: 'hardware',
    name: 'Hardware & Electronics',
    niches: ['hardware', 'semiconductors', 'electrical-engineering', 'electronics-engineering', 'telecommunications'],
    roles: [
      { slug: 'hardware-engineer', name: 'Hardware Engineer', family: 'hardware', aliases: ['Computer Engineer'] },
      { slug: 'electrical-engineer', name: 'Electrical Engineer', family: 'hardware', niche: 'electrical-engineering' },
      { slug: 'electronics-engineer', name: 'Electronics Engineer', family: 'hardware', niche: 'electronics-engineering', aliases: ['PCB Designer'] },
      { slug: 'mechatronics-engineer', name: 'Mechatronics Engineer', family: 'hardware', niche: 'robotics' },
      { slug: 'semiconductor-engineer', name: 'Semiconductor Engineer', family: 'hardware', niche: 'semiconductors', aliases: ['Chip Design Engineer', 'ASIC Engineer', 'FPGA Engineer', 'VLSI Engineer'] },
      { slug: 'rf-engineer', name: 'RF Engineer', family: 'hardware', niche: 'electronics-engineering', aliases: ['Radio Frequency Engineer'] },
      { slug: 'telecommunications-engineer', name: 'Telecommunications Engineer', family: 'hardware', niche: 'telecommunications', aliases: ['Telecom Engineer'] },
      { slug: 'hardware-technician', name: 'Hardware Technician', family: 'hardware', aliases: ['Field Technician'] },
    ],
  },
  {
    slug: 'industrial',
    name: 'Manufacturing & Industrial',
    niches: ['manufacturing', 'industrial-engineering', 'mechanical-engineering', 'chemical-engineering', 'automotive-engineering', 'aerospace-engineering', 'logistics'],
    roles: [
      { slug: 'mechanical-engineer', name: 'Mechanical Engineer', family: 'industrial', niche: 'mechanical-engineering' },
      { slug: 'industrial-engineer', name: 'Industrial Engineer', family: 'industrial', niche: 'industrial-engineering' },
      { slug: 'manufacturing-engineer', name: 'Manufacturing Engineer', family: 'industrial', aliases: ['Production Engineer'] },
      { slug: 'process-engineer', name: 'Process Engineer', family: 'industrial', niche: 'chemical-engineering', aliases: ['Chemical Engineer'] },
      { slug: 'aerospace-engineer', name: 'Aerospace Engineer', family: 'industrial', niche: 'aerospace-engineering', aliases: ['Aeronautical Engineer'] },
      { slug: 'automotive-engineer', name: 'Automotive Engineer', family: 'industrial', niche: 'automotive-engineering' },
      { slug: 'safety-engineer', name: 'Safety Engineer', family: 'industrial', aliases: ['HSE Engineer'] },
      { slug: 'maintenance-engineer', name: 'Maintenance Engineer', family: 'industrial' },
      { slug: 'plant-manager', name: 'Plant Manager', family: 'industrial', aliases: ['Production Manager', 'Factory Manager'] },
    ],
  },
  {
    slug: 'built-environment',
    name: 'Architecture, Construction & Real Estate',
    niches: ['architecture', 'construction', 'civil-engineering', 'real-estate-development', 'commercial-real-estate', 'residential-real-estate', 'property-management', 'real-estate-investing'],
    roles: [
      { slug: 'architect', name: 'Architect', family: 'built-environment' },
      { slug: 'interior-designer', name: 'Interior Designer', family: 'built-environment' },
      { slug: 'landscape-architect', name: 'Landscape Architect', family: 'built-environment' },
      { slug: 'civil-engineer', name: 'Civil Engineer', family: 'built-environment', niche: 'civil-engineering', aliases: ['Structural Engineer', 'Site Engineer', 'Project Engineer'] },
      { slug: 'construction-manager', name: 'Construction Manager', family: 'built-environment', niche: 'construction', aliases: ['Site Manager'] },
      { slug: 'quantity-surveyor', name: 'Quantity Surveyor', family: 'built-environment', niche: 'construction', aliases: ['Surveyor', 'Cost Consultant'] },
      { slug: 'urban-planner', name: 'Urban Planner', family: 'built-environment', aliases: ['Town Planner'] },
      { slug: 'real-estate-analyst', name: 'Real Estate Analyst', family: 'built-environment', niche: 'real-estate-investing' },
      { slug: 'real-estate-agent', name: 'Real Estate Agent', family: 'built-environment', niche: 'residential-real-estate', aliases: ['Realtor', 'Estate Agent', 'Broker'] },
      { slug: 'real-estate-developer', name: 'Real Estate Developer', family: 'built-environment', niche: 'real-estate-development' },
      { slug: 'property-manager', name: 'Property Manager', family: 'built-environment', niche: 'property-management', aliases: ['Facilities Manager'] },
    ],
  },
  {
    slug: 'education',
    name: 'Education',
    niches: ['teaching', 'higher-education', 'edtech', 'academic-research', 'online-education'],
    roles: [
      { slug: 'teacher', name: 'Teacher', family: 'education', aliases: ['Schoolteacher', 'Educator'] },
      { slug: 'professor', name: 'Professor', family: 'education', niche: 'higher-education', aliases: ['Lecturer', 'Assistant Professor', 'Associate Professor', 'Faculty'] },
      { slug: 'tutor', name: 'Tutor', family: 'education', aliases: ['Teaching Assistant', 'TA', 'Private Tutor'] },
      { slug: 'instructional-designer', name: 'Instructional Designer', family: 'education', niche: 'online-education', aliases: ['Curriculum Designer', 'Learning Designer'] },
      { slug: 'education-consultant', name: 'Education Consultant', family: 'education', niche: 'edtech' },
      { slug: 'school-administrator', name: 'School Administrator', family: 'education', aliases: ['Principal (School)', 'Headteacher', 'Dean'] },
      { slug: 'course-creator', name: 'Course Creator', family: 'education', niche: 'online-education', aliases: ['Education Content Creator'] },
    ],
  },
  {
    slug: 'public-sector',
    name: 'Government & Public Sector',
    niches: ['government', 'public-policy', 'international-relations', 'nonprofits'],
    roles: [
      { slug: 'civil-servant', name: 'Civil Servant', family: 'public-sector', aliases: ['Government Officer', 'Administrative Officer', 'IAS', 'IPS'] },
      { slug: 'policy-analyst', name: 'Policy Analyst', family: 'public-sector', niche: 'public-policy', aliases: ['Policy Advisor', 'Public Policy Manager'] },
      { slug: 'diplomat', name: 'Diplomat', family: 'public-sector', niche: 'international-relations', aliases: ['Foreign Service Officer'] },
      { slug: 'public-affairs-manager', name: 'Public Affairs Manager', family: 'public-sector', niche: 'public-policy', aliases: ['Government Relations'] },
      { slug: 'intelligence-analyst', name: 'Intelligence Analyst', family: 'public-sector' },
      { slug: 'police-officer', name: 'Police Officer', family: 'public-sector', aliases: ['Law Enforcement Officer'] },
      { slug: 'military-officer', name: 'Military Officer', family: 'public-sector', niche: 'defence', aliases: ['Armed Forces Officer'] },
      { slug: 'public-health-officer', name: 'Public Health Officer', family: 'public-sector', niche: 'health-management', aliases: ['Epidemiologist'] },
      { slug: 'nonprofit-manager', name: 'Nonprofit Manager', family: 'public-sector', niche: 'nonprofits', aliases: ['NGO Manager', 'Programme Officer', 'Development Manager'] },
    ],
  },
  {
    slug: 'specialised-tech',
    name: 'Specialised Tech',
    niches: ['blockchain', 'gaming', 'ar-vr', 'quantum-computing', 'software-engineering'],
    roles: [
      { slug: 'blockchain-engineer', name: 'Blockchain Engineer', family: 'specialised-tech', aliases: ['Web3 Developer', 'Smart Contract Developer', 'Solidity Developer', 'Protocol Engineer'] },
      { slug: 'crypto-researcher', name: 'Crypto Researcher', family: 'specialised-tech', aliases: ['Tokenomics Researcher'] },
      { slug: 'xr-engineer', name: 'XR Engineer', family: 'specialised-tech', niche: 'ar-vr', aliases: ['AR Engineer', 'VR Engineer', 'Spatial Computing Engineer'] },
      { slug: 'game-developer', name: 'Game Developer', family: 'specialised-tech', niche: 'gaming', aliases: ['Gameplay Engineer', 'Unity Developer', 'Unreal Engine Developer'] },
      { slug: 'game-designer', name: 'Game Designer', family: 'specialised-tech', niche: 'gaming', aliases: ['Level Designer'] },
      { slug: 'graphics-engineer', name: 'Graphics Engineer', family: 'specialised-tech', niche: 'gaming', aliases: ['Rendering Engineer', 'Computer Graphics Researcher'] },
      { slug: 'quantum-engineer', name: 'Quantum Engineer', family: 'specialised-tech', niche: 'quantum-computing', aliases: ['Quantum Software Engineer', 'Quantum Computing Researcher'] },
      { slug: 'distributed-systems-engineer', name: 'Distributed Systems Engineer', family: 'specialised-tech', niche: 'software-engineering', aliases: ['Edge Computing Engineer', 'Storage Engineer', 'Distributed Database Engineer'] },
      { slug: 'compiler-engineer', name: 'Compiler Engineer', family: 'specialised-tech', niche: 'software-engineering', aliases: ['Kernel Engineer', 'Operating Systems Engineer', 'Systems Programmer'] },
      { slug: 'search-engineer', name: 'Search Engineer', family: 'specialised-tech', niche: 'software-engineering', aliases: ['Recommendation Systems Engineer', 'Personalisation Engineer', 'Ranking Engineer'] },
      { slug: 'ads-engineer', name: 'Ads Engineer', family: 'specialised-tech', niche: 'software-engineering', aliases: ['Pricing Engineer', 'Monetisation Engineer'] },
      { slug: 'trust-safety-engineer', name: 'Trust & Safety Engineer', family: 'specialised-tech', niche: 'software-engineering', aliases: ['Fraud Engineer', 'Anti-Abuse Engineer'] },
    ],
  },
]

export const ROLES = ROLE_FAMILIES.flatMap((f) => f.roles)

export const ROLE_BY_SLUG = new Map(ROLES.map((r) => [r.slug, r]))

export const ROLE_FAMILY_BY_SLUG = new Map(ROLE_FAMILIES.map((f) => [f.slug, f]))
